"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
const inter = Inter({ subsets: ["latin"] });
import { createContext } from "react";
import { useState, useEffect } from "react";
import axios from "axios";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface AuthContextType {
  authState: {
    username: string;
    id: number;
    status: boolean;
  };
  setAuthState: React.Dispatch<
    React.SetStateAction<{
      username: string;
      id: number;
      status: boolean;
    }>
  >;
}

const defaultAuthState = {
  username: "",
  id: 0,
  status: false,
};

export const AuthContext = createContext<AuthContextType>({
  authState: defaultAuthState,
  setAuthState: () => {},
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [authState, setAuthState] = useState({
    username: "",
    id: 0,
    status: false,
  });

  useEffect(() => {
    axios
      .get("http://localhost:3001/auth/auth", {
        headers: {
          accessToken: localStorage.getItem("accessToken"),
        },
      })
      .then((response) => {
        if (response.data.error) {
          setAuthState({ ...authState, status: false });
        } else {
          setAuthState({
            username: response.data.username,
            id: response.data.id,
            status: true,
          });
        }
      });
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext.Provider value={{ authState, setAuthState }}>
          <NavBar />
          {children}
        </AuthContext.Provider>
      </body>
    </html>
  );
}
